# Generated by Django 3.2.3 on 2021-10-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
