# Generated by Django 3.2.3 on 2021-10-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_choice_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='expiry',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HOURS:MINUTES:SECONDS, example - 2021-10-16 19:30:51', null=True),
        ),
    ]
